1.a)
z = rnorm(100, 5, sqrt(2))
boxplot(z, horizontal = T)
hist(z)
hist(z, probability = T)
lines(density(z))
x=seq(0, 10, 0.1)
y = dnorm(x, 5, sqrt(2))
lines(x, y, col = 'red')
z = rnorm(1000, 5, sqrt(2))
hist(z, probability = T)
lines(density(z))
lines(x, y, col = 'red')

1.b)
z = runif(100, 1, 5)
boxplot(z, horizontal = T)
hist(z)
hist(z, probability = T)
lines(density(z))

1.c)
z = rexp(100, 3)
boxplot(z) 
hist(z)
hist(z, probability = T)
lines(density(z))

1.d)
z = rgamma(100, 5, 1)
boxplot(z)
boxplot(z, horizontal = T)
hist(z)
hist(z, probability = T)
lines(density(z))
